version: '3.7'
services:

  laravel-docker:
    container_name: laravel-docker-pizzaria
    restart: unless-stopped
    build:
      context: ./backend/
      dockerfile: Dockerfile_dev
    volumes:
      - ./backend:/var/www/html
      - ./backend/etc/php.ini:/usr/local/etc/php/php.ini
      - ./files:/home/files
    ports:
      - 8000:80
    networks:
      - docker

  mysql_database:
    container_name: mysql_database-pizzaria
    restart: unless-stopped
    image: mysql:latest
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/share:/home/share
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - docker

  my_admin:
    container_name: my_admin-pizzaria
    restart: unless-stopped
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOSTS=mysql_database
    networks:
      - docker

#Docker Networks
networks:
  docker:
    driver: bridge
