FROM php:apache-bookworm

WORKDIR /var/www/html

RUN a2enmod rewrite

RUN apt update -y && apt install -y \
    libicu-dev\
    libmariadb-dev\
    unzip zip\
    zlib1g-dev\
    libpng-dev\
    libjpeg-dev\
    libfreetype6-dev\
    libjpeg62-turbo-dev

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN docker-php-ext-install gettext intl pdo_mysql gd

RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# Debugging
RUN pecl install -o -f xdebug && docker-php-ext-enable xdebug
