name: Backend_test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
     - main

jobs:
  tests:
    name: Run tests Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: docker-compose up -d
        run: |
          docker-compose up -d

      - name: Copy .env.ci
        run: |
          docker exec laravel-docker-pizzaria cp .env.ci .env
          
      - name: Composer upgrade
        run: |
          docker exec laravel-docker-pizzaria composer update && docker exec laravel-docker-pizzaria composer upgrade && docker exec laravel-docker-pizzaria apt update && docker exec laravel-docker-pizzaria apt full-upgrade -y    

      - name: Migrate Laravel
        run: |
          docker exec laravel-docker-pizzaria php artisan migrate --force

      - name: Make pizzaria_test
        run: |
          docker exec laravel-docker-pizzaria cp .env.test .env && docker exec laravel-docker-pizzaria php artisan migrate --force && docker exec laravel-docker-pizzaria cp .env.ci .env

      - name: Laravel test
        run: |
          docker exec laravel-docker-pizzaria php artisan test
